### ISSUE TITLE
when removed/uninstalled selfbuild core-apps are repeatedly reinstalled over OpenStore version

### ISSUE THREAD

**Issue by Danfro** [ubports/click#9]
Following up on [this issue](https://gitlab.com/myii/ut-tweak-tool/issues/28#note_164755778) and [this issue](https://gitlab.com/theopenstore/openstore-meta/issues/223#note_163890994) I try filing it here. :smile: 

E5, RC 2019-W09

- build an core-app with clickable (i.e. weather-app, clock, ...)
- install on phone with clickable
- open OpenStore app
- goto updates, that app is shown with a comment that it is not the latest stable version from the app store
- install latest version of app from OpenStore

**expected behavior**
- the latest stable app version from OpenStore is installed and remains installed

**actual behaviour**
- the latest stable version from OpenStore is installed
BUT after a reboot the selfbuild version gets reinstalled automatically

This behaviour applies only to core-apps as far as I found so far.
Quite annoying if your testversion does not work. You end up with an unusable app-version after every reboot.

**Comment by MK1973** [comment]
I confirm the same experience testing new in development weather core-app. 

Tested on: 
- Bq 4.5
- Nexus 5
- Fairphone
 
Channels: 
- RC
- Devel
- Edge

**Comment by dobey** [comment]
I have migrated this issue to https://gitlab.com/ubports/core/click/-/issues/1 for consideration in future development of click. Thanks.
